### ISSUE TITLE
DMX output not working on my DUE 

### ISSUE THREAD

**Issue by philarnaud** [mtongnz/mtDueDMX#4]
Hello,
Thank you for your answer. 
Here is my code and explanations:

//Mycode with Due and your library
#include <mtDueDMX.h>
uint8_t dmxData[512];
uint8_t dmxDirPin = 7; // Pin 7 on DUE

void setup()
{
  mtDueDMX[0]->begin(DMX_TX, dmxData, dmxDirPin);
  mtDueDMX[0]->startOutput();
  dmxData[4] = 255; // set PAR master brightness to max
  dmxData[5] = 255; // set PAR RED to max
}

-The Grove – DMX512 is a adapter from Grove interface to DMX512 interface (industry standard EIA-485 interface. The module is based on SN75176 chip which can balance transmission lines and meet ANSI Standard EIA-485 interface

-Test is done on a small PAR LED RGBW (… 4=Power,5=Red,6=Green,7=Blue…) 

With this very small DUE sample of code,  we can see that a message is read by the PAR LED (very small led in the back is blinking) but not any light is showing up. I tested many other examples, in loops with many color, on other output pins, but nothing is coming.

-For comparison, here is a code working perfectly well with Arduino Uno and same hardware:

#include <DmxSimple.h>

void setup() {
  DmxSimple.maxChannel(100);
  DmxSimple.usePin(3); // Pin 3 on UNO
  DmxSimple.write(4, 255); // set PAR master brightness to max
  DmxSimple.write(5, 255); // set PAR RED to max
}
RED is showing up on PAR

Do you have any idea of what I can check more?
Best regards.
Philippe

**Comment by mtongnz** [comment]
I see you use pin 3 as the TX pin on the uno. Have you got the grove connected to the TX0 on the due? Or the UART connector if using the grove base shield

**Comment by philarnaud** [comment]
I have a yellow cable that was connected on pin 3 on the uno. When I saw your sample, I saw that it was in pin 7, so I just put this yellow cable on pin 7 on the due, nothing else. Is there something else to do? The grove is linked with 3 cables black (ground) red (+5V)  and yellow (TX?)

**Comment by mtongnz** [comment]
Pin 7 is the direction pin as my library allows for dmx in or out (well, it will very soon). You don't need to connect anything here as I think the grove is only output.
Connect the yellow to pin 1 (TX0). Black to GND. Red to 5V.
It should then work. The due is 3.3V so ideally you need a level converter of some sort but it should work.

**Comment by philarnaud** [comment]
Thank you very much for your help, on pin 1 (TX0) your library works perfectly well.  
The small drawback is that serial output monitor is not working anymore and showing cabalistic chars!

**Comment by mtongnz** [comment]
Use tx1 pin and change to mtDueDmx[1]

**Comment by philarnaud** [comment]
Hello Matt,
It's working perfectly well!
Many thanks for your help
Philippe

#include <mtDueDMX.h>
uint8_t dmxData[255];
void setup()
{
Serial.begin(9600);
mtDueDMX[1]->begin(DMX_TX, dmxData,0);
mtDueDMX[1]->startOutput();
Serial.println("Init done");
dmxData[3] = 255; // set PAR master brightness to max

}
void loop()
{
  for (int j = 0; j < 4; j++)
  { 
   Serial.print("Couleur R=0,G=1,B=2,W=3:" );  
   Serial.println(j); 
   delay(1000); 
   for (int i = 1; i < 255; i++)
   {
    dmxData[4+j]= i;
    delay(20);
   }  
   delay(1000); 
   for (int i = 255; i > 0; i--)
   {
    dmxData[4+j]= i;
    delay(10);
   } 
  }
}
